// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

/**
 * =================================================================================
 * FILE: xdp_packet_filter_bpfeb.go
 * MÔ TẢ: Bridge trung gian phiên bản Big Endian (bpfeb).
 * LUỒNG HOẠT ĐỘNG: 
 *   Tương tự phiên bản Little Endian, file này quản lý việc nạp bytecode eBPF vào 
 *   Kernel nhưng dành cho các kiến trúc phần cứng có thứ tự byte ngược lại.
 * TẠI SAO CÓ HAI FILE?
 *   eBPF bytecode là mã máy ảo. Tùy vào CPU đích, thứ tự các byte trong số nguyên 
 *   (Endianness) sẽ khác nhau. bpf2go tạo ra cả hai để đảm bảo tính tương thích chéo.
 * =================================================================================
 */

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

/**
 * # ĐỊNH NGHĨA STRUCT DỮ LIỆU
 * Các struct này là "hợp đồng" về cấu trúc bộ nhớ giữa Go và mã C trong Kernel.
 */

type xdp_packet_filterIpv4LpmKey struct {
	// _ structs.HostLayout: Rất quan trọng để ngăn Go Compiler tự ý tối ưu hóa 
	// khoảng cách các trường (field padding), giúp struct này khớp tuyệt đối với C struct.
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type xdp_packet_filterRuleId struct {
	_        structs.HostLayout
	SubnetId uint32
	Proto    int32
	Port     uint32
}

/**
 * # BƯỚC 1: ĐỌC ĐỊNH NGHĨA (CollectionSpec)
 * Hàm này giải mã file .o (object file) để Go hiểu được trong đó có bao nhiêu Map, 
 * bao nhiêu Program và các yêu cầu về tài nguyên của chúng.
 */
func loadXdp_packet_filter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_packet_filterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_packet_filter: %w", err)
	}

	return spec, err
}

/**
 * # BƯỚC 2: NẠP VÀ GÁN ĐỐI TƯỢNG (LoadAndAssign)
 * Đây là hàm thực hiện công việc nặng nhọc nhất:
 *   1. Thực hiện các Syscall (hệ thống) để yêu cầu Kernel tạo Map và nạp mã XDP.
 *   2. Verifier của Kernel sẽ kiểm tra tính an toàn của mã tại đây.
 *   3. Nếu thành công, nó sẽ ánh xạ các File Descriptors vào struct 'obj'.
 */
func loadXdp_packet_filterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_packet_filter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_packet_filterSpecs chứa các cấu hình Map/Program trước khi chúng được "sống" trong Kernel.
type xdp_packet_filterSpecs struct {
	xdp_packet_filterProgramSpecs
	xdp_packet_filterMapSpecs
	xdp_packet_filterVariableSpecs
}

type xdp_packet_filterProgramSpecs struct {
	XdpPacketFilter *ebpf.ProgramSpec `ebpf:"xdp_packet_filter"`
}

type xdp_packet_filterMapSpecs struct {
	DefaultActionMap *ebpf.MapSpec `ebpf:"default_action_map"`
	RuleMap          *ebpf.MapSpec `ebpf:"rule_map"`
	SubnetMap        *ebpf.MapSpec `ebpf:"subnet_map"`
}

type xdp_packet_filterVariableSpecs struct {
}

/**
 * # QUẢN LÝ ĐỐI TƯỢNG RUNTIME
 * Struct này giữ các liên kết đến tài nguyên thực tế đang chạy trong Kernel.
 */
type xdp_packet_filterObjects struct {
	xdp_packet_filterPrograms
	xdp_packet_filterMaps
	xdp_packet_filterVariables
}

/**
 * # GIẢI PHÓNG TÀI NGUYÊN (Close)
 * CẠM BẪY: Trong Linux, các đối tượng eBPF được quản lý bằng File Descriptors (FD).
 * Nếu ứng dụng Go của bạn thoát mà không gọi Close(), các FD này có thể bị rò rỉ.
 * Mặc dù Kernel hiện đại sẽ tự dọn dẹp khi process chết, nhưng việc Close chủ động
 * giúp đảm bảo hệ thống ổn định trong các kịch bản Reload firewall liên tục.
 */
func (o *xdp_packet_filterObjects) Close() error {
	return _Xdp_packet_filterClose(
		&o.xdp_packet_filterPrograms,
		&o.xdp_packet_filterMaps,
	)
}

type xdp_packet_filterMaps struct {
	DefaultActionMap *ebpf.Map `ebpf:"default_action_map"`
	RuleMap          *ebpf.Map `ebpf:"rule_map"`
	SubnetMap        *ebpf.Map `ebpf:"subnet_map"`
}

func (m *xdp_packet_filterMaps) Close() error {
	return _Xdp_packet_filterClose(
		m.DefaultActionMap,
		m.RuleMap,
		m.SubnetMap,
	)
}

type xdp_packet_filterVariables struct {
}

type xdp_packet_filterPrograms struct {
	XdpPacketFilter *ebpf.Program `ebpf:"xdp_packet_filter"`
}

func (p *xdp_packet_filterPrograms) Close() error {
	return _Xdp_packet_filterClose(
		p.XdpPacketFilter,
	)
}

// Vòng lặp đóng các tài nguyên. 
// Nếu một cái thất bại, nó vẫn cố gắng đóng các cái còn lại để tránh rò rỉ tối đa.
func _Xdp_packet_filterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

/**
 * # NHÚNG BYTECODE (Big Endian)
 * go:embed xdp_packet_filter_bpfeb.o
 * File này chứa mã máy eBPF đã được biên dịch với flag -target bpfeb.
 */
var _Xdp_packet_filterBytes []byte