// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

/**
 * =================================================================================
 * FILE: xdp_packet_filter_bpfel.go
 * MÔ TẢ: Bridge trung gian giữa Go (User-space) và eBPF (Kernel-space).
 * LUỒNG HOẠT ĐỘNG:
 *   1. Nhúng file object đã biên dịch (.o) vào binary Go thông qua `go:embed`.
 *   2. Định nghĩa các Struct tương ứng với mã C để trao đổi dữ liệu qua Maps.
 *   3. Cung cấp các hàm Helper để nạp (load) chương trình vào Kernel và ánh xạ (assign)
 *      vào các biến Go để dễ dàng điều khiển.
 * KIẾN TRÚC: bpfel (BPF Little Endian) - Dành cho các CPU như x86_64 hoặc ARM64.
 * =================================================================================
 */

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

/**
 * # CẤU TRÚC DỮ LIỆU ĐỒNG BỘ
 * TẠI SAO: Các struct này phải khớp hoàn toàn 1:1 về kích thước và thứ tự bộ nhớ (memory layout)
 * với các struct định nghĩa trong file C (xdp-filter.c).
 * 
 * CẠM BẪY: Nếu kích thước khác nhau (ví dụ: do padding), khi bạn ghi dữ liệu từ Go vào Map,
 * Kernel sẽ đọc sai giá trị hoặc từ chối thực thi do lỗi sai lệch địa chỉ vùng nhớ.
 */

type xdp_packet_filterIpv4LpmKey struct {
	// _ structs.HostLayout đảm bảo Go không tự ý thay đổi thứ tự các field để tối ưu hóa bộ nhớ,
	// giữ nguyên cấu trúc để phù hợp với định dạng mà Kernel eBPF mong đợi.
	_         structs.HostLayout
	Prefixlen uint32 // Phải khớp với __u32 prefixlen trong C
	Addr      uint32 // Phải khớp với __u32 addr trong C
}

type xdp_packet_filterRuleId struct {
	_        structs.HostLayout
	SubnetId uint32
	Proto    int32
	Port     uint32
}

/**
 * # BƯỚC 1: NẠP BẢN THIẾT KẾ (CollectionSpec)
 * Hàm này đọc dữ liệu bytecode eBPF đã được nhúng và phân tích nó thành một "bản thiết kế".
 * Nó chưa đẩy bất cứ thứ gì vào Kernel, chỉ đơn giản là chuẩn bị các tham số nạp.
 */
func loadXdp_packet_filter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Xdp_packet_filterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp_packet_filter: %w", err)
	}

	return spec, err
}

/**
 * # BƯỚC 2: HIỆN THỰC HÓA VÀ ÁNH XẠ (LoadAndAssign)
 * Đây là lúc "phép màu" xảy ra. Hàm này thực hiện các Syscall (thường là `bpf()`) để:
 *   - Nạp chương trình vào Kernel để Verifier kiểm tra.
 *   - Tạo các Maps trong bộ nhớ Kernel.
 *   - Liên kết các File Descriptor (FD) từ Kernel vào các trường trong struct `obj`.
 */
func loadXdp_packet_filterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp_packet_filter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdp_packet_filterSpecs chứa các định nghĩa thô trước khi nạp.
type xdp_packet_filterSpecs struct {
	xdp_packet_filterProgramSpecs
	xdp_packet_filterMapSpecs
	xdp_packet_filterVariableSpecs
}

// xdp_packet_filterProgramSpecs định nghĩa các chương trình XDP sẽ được nạp.
type xdp_packet_filterProgramSpecs struct {
	// Tên trong tag `ebpf:"xdp_packet_filter"` phải khớp chính xác với SEC("xdp") trong C.
	XdpPacketFilter *ebpf.ProgramSpec `ebpf:"xdp_packet_filter"`
}

// xdp_packet_filterMapSpecs định nghĩa các Map sẽ được tạo trong Kernel.
type xdp_packet_filterMapSpecs struct {
	DefaultActionMap *ebpf.MapSpec `ebpf:"default_action_map"`
	RuleMap          *ebpf.MapSpec `ebpf:"rule_map"`
	SubnetMap        *ebpf.MapSpec `ebpf:"subnet_map"`
}

type xdp_packet_filterVariableSpecs struct {
}

/**
 * # QUẢN LÝ ĐỐI TƯỢNG (Objects)
 * Struct này chứa các đối tượng eBPF "đã sống" trong Kernel.
 * Bạn sẽ dùng struct này trong file `main.go` để tương tác với firewall.
 */
type xdp_packet_filterObjects struct {
	xdp_packet_filterPrograms
	xdp_packet_filterMaps
	xdp_packet_filterVariables
}

// Close() là cực kỳ quan trọng. 
// TẠI SAO: eBPF sử dụng File Descriptors (FD). Nếu bạn không đóng khi thoát chương trình,
// các tài nguyên này có thể bị treo lại trong Kernel (Resource Leak), 
// khiến card mạng có thể bị kẹt ở chế độ XDP ngay cả khi ứng dụng đã tắt.
func (o *xdp_packet_filterObjects) Close() error {
	return _Xdp_packet_filterClose(
		&o.xdp_packet_filterPrograms,
		&o.xdp_packet_filterMaps,
	)
}

type xdp_packet_filterMaps struct {
	DefaultActionMap *ebpf.Map `ebpf:"default_action_map"`
	RuleMap          *ebpf.Map `ebpf:"rule_map"`
	SubnetMap        *ebpf.Map `ebpf:"subnet_map"`
}

func (m *xdp_packet_filterMaps) Close() error {
	return _Xdp_packet_filterClose(
		m.DefaultActionMap,
		m.RuleMap,
		m.SubnetMap,
	)
}

type xdp_packet_filterVariables struct {
}

type xdp_packet_filterPrograms struct {
	XdpPacketFilter *ebpf.Program `ebpf:"xdp_packet_filter"`
}

func (p *xdp_packet_filterPrograms) Close() error {
	return _Xdp_packet_filterClose(
		p.XdpPacketFilter,
	)
}

// Hàm bổ trợ để đóng hàng loạt các Closer (Maps, Programs).
func _Xdp_packet_filterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

/**
 * # NHÚNG BYTECODE
 * go:embed xdp_packet_filter_bpfel.o
 * Dòng này lấy file mã máy đã biên dịch (object file) và đóng gói nó trực tiếp 
 * vào file thực thi cuối cùng. Người dùng sẽ không cần mang theo file .o khi chạy firewall.
 */
var _Xdp_packet_filterBytes []byte